# Generated by Django 5.0.4 on 2024-05-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.CharField(default='', max_length=150),
        ),
    ]
